version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  ignore:
  - dependency-name: metascraper-description
    versions:
    - 5.16.16
    - 5.18.1
    - 5.18.12
    - 5.18.2
    - 5.18.4
    - 5.18.5
    - 5.18.6
    - 5.18.9
    - 5.20.0
    - 5.21.0
    - 5.21.2
    - 5.21.3
    - 5.21.4
    - 5.21.5
  - dependency-name: metascraper-publisher
    versions:
    - 5.16.16
    - 5.18.1
    - 5.18.12
    - 5.18.2
    - 5.18.4
    - 5.18.5
    - 5.18.6
    - 5.18.9
    - 5.20.0
    - 5.21.0
    - 5.21.2
    - 5.21.3
    - 5.21.4
    - 5.21.5
  - dependency-name: metascraper-logo
    versions:
    - 5.16.16
    - 5.18.1
    - 5.18.12
    - 5.18.2
    - 5.18.4
    - 5.18.5
    - 5.18.6
    - 5.18.9
    - 5.20.0
    - 5.21.0
    - 5.21.2
    - 5.21.3
    - 5.21.4
    - 5.21.5
  - dependency-name: metascraper-author
    versions:
    - 5.16.16
    - 5.18.1
    - 5.18.12
    - 5.18.2
    - 5.18.4
    - 5.18.5
    - 5.18.6
    - 5.18.9
    - 5.20.0
    - 5.21.0
    - 5.21.2
    - 5.21.3
    - 5.21.4
    - 5.21.5
  - dependency-name: metascraper-title
    versions:
    - 5.16.16
    - 5.18.1
    - 5.18.12
    - 5.18.2
    - 5.18.4
    - 5.18.5
    - 5.18.6
    - 5.18.9
    - 5.20.0
    - 5.21.0
    - 5.21.2
    - 5.21.3
    - 5.21.4
    - 5.21.5
